.ALIASES
R_R2            R2(1=0 2=WITH_NOISE ) CN @RANDOM_NOISE.SCHEMATIC1(sch_1):INS289@ANALOG.R.Normal(chips)
V_V4            V4(+=CLEAN -=0 ) CN @RANDOM_NOISE.SCHEMATIC1(sch_1):INS392@SOURCE.VDC.Normal(chips)
E_E1            E1(OUT+=WITH_NOISE OUT-=CLEAN ) CN @RANDOM_NOISE.SCHEMATIC1(sch_1):INS602@ABM.EVALUE.Normal(chips)
_    _(Clean=CLEAN)
_    _(With_Noise=WITH_NOISE)
.ENDALIASES
